title:            Kabir Sewani || @beeriest 
url:              kabirsewani.com
permalink:        pretty
pygments:         false
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-44880705-1
timezone:         Canada/Toronto
paginate: 5
links: 
  - name:         About
    url:          /about
  - name:         Work
    url:          /work